"""FROZEN shared data contracts (v1) for the UpayShield backend.

Both backend parts import from here. Do NOT edit this file in a feature branch.
Backward-compatible additions (new *optional* fields) go through the lead via a
`chore(contract): ...` commit on `main`.  Part-specific models live in
`schemas_core.py` (Part 1) and `schemas_intel.py` (Part 2).
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Generic, Literal, TypeVar

from pydantic import BaseModel, ConfigDict, Field

Scalar = str | int | float | bool | None
Language = Literal["en", "bn"]
TxnType = Literal["CASH_IN", "CASH_OUT", "TRANSFER", "PAYMENT"]
CONTRACT_VERSION = "1.0"


class _M(BaseModel):
    # extra="ignore": ML-module dicts may carry extra keys.
    # protected_namespaces=(): we have a field called `model_score`.
    model_config = ConfigDict(extra="ignore", protected_namespaces=())


# ------------------------------------------------------------------ enums
class Action(str, Enum):
    ALLOW = "allow"
    OTP_STEP_UP = "otp_step_up"
    HOLD = "hold"
    ESCALATE = "escalate"          # hold + route to senior analyst / compliance
    BLOCK = "block"
    FREEZE_WALLET = "freeze_wallet"


# Policies may only RAISE severity, never lower it (unit-test this property).
ACTION_SEVERITY: dict[Action, int] = {
    Action.ALLOW: 0, Action.OTP_STEP_UP: 1, Action.HOLD: 2,
    Action.ESCALATE: 3, Action.BLOCK: 4, Action.FREEZE_WALLET: 5,
}


class RiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# severity -> level (allow=low, otp=medium, hold/escalate=high, block/freeze=critical)
SEVERITY_TO_LEVEL: dict[int, RiskLevel] = {
    0: RiskLevel.LOW, 1: RiskLevel.MEDIUM, 2: RiskLevel.HIGH,
    3: RiskLevel.HIGH, 4: RiskLevel.CRITICAL, 5: RiskLevel.CRITICAL,
}


class AlertType(str, Enum):
    ACCOUNT_TAKEOVER = "account_takeover"
    OTP_BREACH = "otp_breach"        # OTP shared with / intercepted by someone else
    GAMBLING = "gambling"            # payments to betting services
    SCAM = "scam"
    MULE_NETWORK = "mule_network"
    AGENT_ANOMALY = "agent_anomaly"
    STRUCTURING = "structuring"
    ANOMALY = "anomaly"            # flagged by the model, no named pattern


# Deterministic precedence when several tags fire (first match wins).
ALERT_TYPE_PRECEDENCE = [AlertType.OTP_BREACH, AlertType.ACCOUNT_TAKEOVER, AlertType.SCAM, AlertType.MULE_NETWORK,
                         AlertType.AGENT_ANOMALY, AlertType.STRUCTURING, AlertType.GAMBLING, AlertType.ANOMALY]
# ML rule tags (ml/rules.py) -> alert type
TAG_TO_ALERT_TYPE: dict[str, AlertType] = {
    "account_takeover": AlertType.ACCOUNT_TAKEOVER, "scam_victim": AlertType.SCAM,
    "mule_passthrough": AlertType.MULE_NETWORK, "mule_network": AlertType.MULE_NETWORK,
    "agent_risk": AlertType.AGENT_ANOMALY, "structuring": AlertType.STRUCTURING,
    "otp_breach": AlertType.OTP_BREACH, "sim_swap": AlertType.ACCOUNT_TAKEOVER,
    "gambling": AlertType.GAMBLING, "gambling_repeat": AlertType.GAMBLING,
}


class CaseStatus(str, Enum):
    OPEN = "open"
    CONFIRMED = "confirmed"
    DISMISSED = "dismissed"
    ESCALATED = "escalated"


class Verdict(str, Enum):
    CONFIRM = "confirm"
    DISMISS = "dismiss"


# ------------------------------------------------------------------ raw input
class Transaction(_M):
    """Raw transaction. Columns mirror data/transactions.csv (minus labels)."""
    txn_id: str | None = None          # server assigns LIVE-xxxxxxxx when omitted
    ts: datetime
    user_id: str
    type: TxnType
    amount: float = Field(gt=0)
    recipient_id: str
    agent_id: str | None = None
    device_id: str
    location: str
    balance_before: float = Field(ge=0)
    # --- optional context. Omitted -> treated as "normal / unknown" by the model
    merchant_category: str | None = None      # what the money is for: grocery, utilities, ..., gambling
    otp_requests_10m: int | None = Field(None, ge=0)
    otp_failures_10m: int | None = Field(None, ge=0)
    otp_device_mismatch: int | None = Field(None, ge=0, le=1)   # 1 = OTP confirmed from another device than requested
    concurrent_sessions: int | None = Field(None, ge=1)
    sim_swap_recent: int | None = Field(None, ge=0, le=1)       # 1 = SIM changed in the last 72h


# ------------------------------------------------------------------ ML output (ml/score.py)
class WhatHappened(_M):
    type: str
    amount_bdt: float
    recipient: str
    device: str
    location: str
    time: str                          # "YYYY-MM-DD HH:MM:SS" exactly as the ML module emits it
    agent: str | None = None
    merchant_category: str | None = None   # grocery / utilities / ... / gambling (None for P2P and cash)
    purpose: str | None = None             # what the money is for: betting, utilities, person_to_person, ...


class RiskReason(_M):                  # SHAP factor
    feature: str
    value: float
    shap: float
    text: str


class RuleHit(_M):
    rule_id: str
    tag: str
    text: str


class GraphSignals(_M):
    """Point-in-time network evidence for one wallet (produced by Part 2)."""
    wallet_id: str
    as_of: datetime | None = None
    ring_id: str | None = None
    ring_score: float = Field(0.0, ge=0, le=1)
    community_id: int | None = None
    fan_in: int = 0                    # distinct senders into this wallet (window)
    fan_out: int = 0                   # distinct recipients out of this wallet (window)
    passthrough_ratio: float = 0.0     # outflow / inflow in window, capped at 2.0
    median_dwell_seconds: float | None = None   # inbound -> outbound delay
    shared_device_accounts: int = 0
    flags: list[str] = []              # fan_in_hub, rapid_passthrough, shared_device, ring_member, cashout_exit
    evidence_ids: list[str] = []


class AgentRisk(_M):
    """Peer-relative agent risk (produced by Part 2)."""
    agent_id: str
    as_of: datetime | None = None
    risk_score: float = Field(0.0, ge=0, le=1)
    peer_group: str = "all"
    peer_percentile: float = Field(0.0, ge=0, le=1)
    metrics: dict[str, float] = {}     # cashout_ratio, night_share, near_threshold_share, burst_ratio, volume_z ...
    flags: list[str] = []              # night_burst, structuring_cluster, cashout_skew, volume_spike
    evidence_ids: list[str] = []


class WhyRisky(_M):
    risk_score: float
    model_score: float
    anomaly_score: float
    reasons: list[RiskReason] = []
    rule_trace: list[RuleHit] = []
    tags: list[str] = []
    graph: GraphSignals | None = None  # filled by backend
    agent: AgentRisk | None = None     # filled by backend


class MLDecision(_M):
    action: Action


class MLScore(_M):
    """Exactly what `ml.score.RiskEngine.score_frame()` returns per transaction."""
    txn_id: str
    user_id: str
    what_happened: WhatHappened
    why_risky: WhyRisky
    what_next: MLDecision


# ------------------------------------------------------------------ backend decision
class PolicyHit(_M):
    policy_id: str                     # e.g. POL_RING_FREEZE
    text: str
    raises_to: Action | None = None


class Decision(_M):
    action: Action
    risk_level: RiskLevel
    base_action: Action                # what the ML thresholds alone would do
    alert_type: AlertType | None = None
    policy_trace: list[PolicyHit] = []
    requires_analyst: bool = False
    priority: float = 0.0              # risk_score * amount_bdt
    thresholds_version: str = "model"


class ScoredTransaction(_M):
    """The 'what happened / why risky / what next' triad. Returned by /score, cases and the stream."""
    txn_id: str
    user_id: str
    case_id: str | None = None         # set when an alert case exists
    what_happened: WhatHappened
    why_risky: WhyRisky
    what_next: Decision


# ------------------------------------------------------------------ cases
class Feedback(_M):
    case_id: str
    verdict: Verdict
    analyst: str = "analyst"
    note: str | None = None
    created_at: datetime | None = None


class Case(_M):
    case_id: str                       # "CASE-" + txn_id suffix, e.g. CASE-0062110
    status: CaseStatus = CaseStatus.OPEN
    created_at: datetime
    updated_at: datetime
    alert_type: AlertType | None = None
    priority: float = 0.0
    scored: ScoredTransaction
    feedback: list[Feedback] = []


# ------------------------------------------------------------------ envelopes
T = TypeVar("T")


class Page(BaseModel, Generic[T]):
    items: list[T]
    total: int
    next_cursor: str | None = None


class ErrorBody(_M):
    code: str                          # "case_not_found", "validation_error", "llm_unavailable", ...
    message: str
    details: dict | None = None


class ErrorResponse(_M):
    error: ErrorBody
